cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    julian678:
      email: jubue@gmx.net
      failed_login_attempts: 0
      id: 515d9987bf31db27ba578b03aa5326ef
      logged_in: false
      name: Julian
      password: $2b$12$AcU8JFC.bxkTzfvMlv3YlecoIs6tcm4YNtZ1lKDjyZF163jnlqUnC

preauthorized:
  emails: null
